# Configuración básica
title: "LA FRACTURA"
baseurl: ""  # Deja vacío si tu sitio está en la raíz
url: "https://lafractura.com.ar"
timezone: "America/Argentina/Buenos_Aires"

# Configuración de Markdown
markdown: kramdown

# Configuración de Jekyll
permalink: /:categories/:title/
collections:
  posts:
    output: true
    permalink: /:collection/:title/

# Configuración por defecto
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Equipo La Fractura"

# Excluir archivos
exclude:
  - README.md
  - admin/
  - node_modules/
  - vendor/
  - .jekyll-cache/
