backend:
  name: git-gateway
  branch: main

media_folder: "imagenes/uploads"
public_folder: "/imagenes/uploads"

collections:
  - name: "articulos"
    label: "Artículos"
    folder: "articulos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Fecha de publicación", name: "fecha", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Autor", name: "autor", widget: "string", required: false}
      - {label: "Categoría", name: "categoria", widget: "select", options: ["territorio", "energia", "politica", "ambiente", "pueblos_originarios"]}
      - {label: "Bajada", name: "bajada", widget: "text", required: false}
      - {label: "Imagen destacada", name: "imagen", widget: "image", required: false}
      - {label: "Tiempo de lectura (minutos)", name: "tiempoLectura", widget: "number", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}
